
const realWords1 = [
  "HOUSE", "CHAIR", "TABLE", "APPLE", "BREAD",
  "ELITE", "COVER", "STONE", "GRASS", "SOLID",
  "SHIFT", "DRILL", "PAINT", "ROUGH", "CHECK",
  "ANGRY", "STILL", "AWARD", "BLOCK", "SUPER",
  "BELOW", "WOUND", "APART", "PRIOR", "BASES",
  "TRULY", "LUNCH", "VISIT", "MUSIC", "SHALL",
  "SMITH", "STATE", "TRIAL", "VALUE", "TRADE",
  "HEART", "WASTE", "YOUTH", "LIGHT", "ACTOR",
  "ABUSE", "PROUD", "VITAL", "PLANE", "CREAM",
  "ALONE", "WORTH", "DRESS", "CRAFT", "DEBUT",
  "USAGE", "YOUNG", "ACUTE", "GROSS", "LEASE",
  "CHOSE", "BEING", "FUNNY", "ROUND", "FULLY",
  "STYLE", "PANEL", "NOISE", "NORTH", "SIGHT",
  "DEALT", "TIRED", "TRUTH", "PEACE", "KNOWN",
  "LOOSE", "BROKE", "CHASE", "SMILE", "BRAND",
  "RIGHT", "WORSE", "EQUAL", "HEAVY", "SHOWN",
  "ALONG", "SHARE", "COUNT", "BEGUN", "POWER",
  "MEDIA", "WOMEN", "GLOBE", "ADULT", "FLASH",
  "SCALE", "DRAWN", "OFTEN", "QUEEN", "LEARN",
  "FAITH", "STAGE", "GIVEN", "DELAY", "UNION",
  "CHART", "SMALL", "SEVEN", "GRACE", "ABOVE",
  "PRIME", "DOUBT", "THESE", "CURVE", "THREE",
  "SHELF", "GLASS", "LOWER", "AVOID", "RAPID",
  "FRESH", "BOARD", "BLIND", "THERE", "RAISE",
  "POUND", "MINUS", "BEGAN", "STORY", "MOUNT",
  "DATED", "DRIVE", "SPEND", "AGENT", "SMART",
  "GRAND", "CROSS", "BRING", "SPARE", "LABEL",
  "FOUND", "HORSE", "MOUSE", "BUILD", "HOTEL",
  "ALERT", "ENTER", "SHIRT", "MINOR", "TOUGH",
  "UNTIL", "STUFF", "SHAPE", "THROW", "THIRD",
  "STEEL", "LINKS", "TEXAS", "FIFTH", "ROUTE",
  "SIXTY", "LASER", "AUDIO", "STOCK", "PRINT",
  "FLEET", "DRINK", "EXIST", "TITLE", "SPEED",
  "WATER", "FALSE", "CLAIM", "SOUTH", "GROUP",
  "BOOST", "PARTY", "SPEAK", "SUITE", "METAL",
  "TOTAL", "DROVE", "EIGHT", "GUARD", "SOLVE",
  "USUAL", "THANK", "RADIO", "STAND", "HAPPY",
  "THICK", "WHITE", "AWARE", "INNER", "AGREE",
  "TRUCK", "MAYOR", "STICK", "CATCH", "FIRST",
  "DOING", "WRITE", "THEFT", "CHAIN", "WHERE",
  "SHOCK", "DANCE", "NOVEL", "VALID", "START",
  "CHEST", "MIXED", "DRAFT", "NURSE", "SHORT",
  "BLAME", "EMPTY", "PILOT", "BENCH", "OUGHT",
  "SCOPE", "POINT", "COURT", "COAST", "TREAT",
  "SERVE", "SCORE", "BOOTH", "LATER", "CLEAR",
  "FINAL", "GUIDE", "TOPIC", "ADOPT", "CRIME",
  "ABOUT", "ALBUM", "FOCUS", "ROGER", "VIRUS",
  "LEVEL", "ERROR", "EARLY", "TOUCH", "PRESS",
  "PITCH", "CHEAP", "MARCH", "CLOCK", "MONEY",
  "ENTRY", "WHILE"
];

const nonWords1 = [
  "DREVE", "CHASK", "GRONT", "SLARP", "SWISK",
  "PLIVE", "TROKE", "STUME", "BRALE", "GLORE",
  "SPLON", "FRAVE", "SNICKE", "GROLE", "FLURN",
  "SWARK", "BRINEP", "SPLIG", "TRERN", "GRALM",
  "CLOVNE", "FLIRM", "BRISP", "SNARN", "PRULDE",
  "BLAPE", "CRIVE", "GROBE", "SNILT", "TWOME",
  "FLERM", "BRUNLT", "SNORN", "CHINT", "GLAPE",
  "SLIVE", "BROPE", "SWIASH", "SKINT", "STIBE",
  "GLISK", "DRENT", "CLOME", "FRIKE", "TROSH",
  "BRISH", "SNISP", "CLANT", "SKORN", "BLARN",
  "PLISH", "DROBE", "FRUSH", "STALM", "SNOVE",
  "TWIRK", "PLAVE", "CLERM", "FLUNE", "GRODE",
  "TRAFE", "DRAVE", "SLABE", "PRIKE", "FLORN",
  "GLUST", "SKARN", "SNERM", "FLABE", "CLOND",
  "TRISEH", "DRERN", "PLUDE", "SNEARK", "SKAPE",
  "GLARP", "SLERM", "TWINT", "CHISK", "BRIME",
  "GLEBE", "CRORN", "FLONT", "STOPE", "DROSE",
  "SNUCQK", "PLERM", "TRABE", "BLIKE", "FLOVE",
  "SWINT", "CLAFE", "GRASH", "TRUVE", "SLUFSH",
  "PRILM", "GROST", "SNIKE", "PLOME", "DRICK",
  "BLERM", "SKINE", "STARN", "FRONAD", "GLAVE",
  "CLIMET", "SNORTE", "TRUWDE", "BROVE", "CHARK",
  "PLAFE", "DROLE", "GRIVE", "SLOME", "FRINT",
  "SWERN", "GLISP", "PLINT", "TRORVE", "SNADE",
  "CRUME", "BLIVE", "PRABE", "FLARN", "CLUNE",
  "SKOPE", "GLARN", "BROLE", "SNUTE", "TWISP",
  "FLUDE", "STORN", "CLAPE", "GRORN", "SNIVE",
  "PLORN", "GLEVE", "SMISK", "DROFE", "FLANT",
  "CLIVET", "BRUME", "SWICK", "GLONE", "VEQOV",
  "DIPAG", "BACAL", "NEYIX", "XIDOW", "XUPIL",
  "PERUG", "TUQAX", "FABEZ", "WACIS", "MORUQ",
  "GAGIZ", "NEHED", "XEBOJ", "GOWOB", "RUGIB",
  "VUGAZ", "YEYEG", "TOWAX", "JIFUJ", "CUQAV",
  "PEROJ", "YAJUB", "LESEB", "BESIZ", "XURAS",
  "BOLIV", "SACEF", "JOXOT", "FODEM", "COCUM",
  "TEDOW", "JINOR", "HEHUJ", "XOPEZ", "QATIQ",
  "GAZIQ", "DUBUW", "HEFEP", "LUKIN", "MUDUJ",
  "QEXAH", "BOQOS", "COHOX", "RIVUN", "VUKOD",
  "GAVAL", "YOJES", "HUHUK", "COBAL", "POSUX",
  "XAYIQ", "ZAMEZ", "TESOR", "HUBOM", "QIGUW",
  "SUFOD", "MOHUQ", "YASAM", "JUYED", "ZUDEM",
  "TITOQ", "HIRAR", "ZEWAK", "KOJEY", "KINAG",
  "ZUZEF", "WEVEC", "XEWOQ", "MELOS", "YAQOB",
  "HADAS", "FOPOJ", "QATUK", "MACAX", "BEROL",
  "QASOH", "TUFAX", "TABIC", "WANAX", "DALOK",
  "JAHOP", "YEKOR", "FODOS", "GUTOG", "QONAK",
  "TAQUC", "WOZUW", "YAPUC", "DUGIF", "GETIK",
  "BIGOQ", "YOJUB", "GIZIK", "LELEN", "HUSIJ",
  "CARAQ", "QAXUW", "GENEIS", "SIPAL", "BAFUP",
  "DAPUP", "COMEC", "BUSUS", "VOZAJ", "ZEYIS",
  "MIMAN", "QODUD", "FUROX", "LISEV", "PAKOS",
  "PARUJ", "VOLUR", "HONAX", "TICAP", "HUFIK",
  "NEHEH", "WOPAD", "PEBAY", "LAVEQ", "DIVAQ",
  "FIQOZ", "YIPIG", "WUJES", "SASIZ", "TIGUH",
  "FAYOJ", "QUNAC", "QOFEM", "LOQEX", "GEKEC",
  "BICEM", "GUSEP", "WAGIR", "TUXAJ", "TAPUX",
  "JOYUN", "GINUF", "MUDIM", "PIYAD", "QOXAS",
  "MUVIH", "KOXUS", "KACOC", "HUJAZ", "MIJUW",
  "QAROG", "XEVAV", "MONID", "QIGOL", "BUZUS",
  "ROHUQ", "QALUD", "BORIZ", "HIZUR", "XANAF",
  "PIMOS", "KURAL", "PAKER", "RETOM", "HUTIP",
  "SESUW", "TATIB", "VIPEG", "ZURIT", "GOYEC",
  "PUQUV", "ZOKOV", "GULAY", "SOMOC", "SILON",
  "MUDUR", "ZAPOX", "YUGAY", "DAYOD", "BAKUN",
  "HALOD", "PAHAM", "VADEL", "CATUD", "XOKUF",
  "YURAX", "KAWIH", "NOFEG", "CAXEZ", "ZATIZ",
  "TAGEQ", "QACUY", "METIM", "YURON", "WOMUG",
  "DERER", "BUJIG", "YULIW", "FUCEQ", "CIBUW",
  "MIYUZ", "RORUM", "MUZIX", "WOLIF", "BIPAN",
  "XIKUQ", "RORUS", "WEZOW", "DADEP", "WECUW",
  "WUMIV", "SAZOM", "RAXOB", "VEJAB", "JULEX",
  "QAXIW", "XIQEW", "DATET", "RUWIZ", "QESIQ",
  "TEPAB", "JIMIR", "HACIV", "KOPAV", "DEWOD",
  "SAHOV", "CAVOT", "BUTAQ", "JUSEJ", "WEFUZ",
  "DIJUQ", "JUWIQ", "VUVUQ", "LOCUUM", "MACAJ",
  "KAVUP", "RUBUB", "DUHAL", "LOZIW", "CATOX",
  "TUSAC", "DIYEG", "HUVUD", "ZIVEP", "YUWEW",
  "NADIG", "SAJEP", "GEHOM", "DUVOX", "ZOJOJ",
  "HAVOV", "WESUB", "VODEW", "COGEQ"
];

const realWords2 = [
  "ARRAY", "ASSET", "MORAL", "EVENT", "FLUID",
  "BLACK", "ALTER", "CLASS", "THING", "ARISE",
  "SWEET", "BRAIN", "CABLE", "TEACH", "YEARS",
  "TIGHT", "FLOOR", "BEGIN", "TIMES", "TRIED",
  "SHELL", "BIRTH", "WHOSE", "SIXTH", "PETER",
  "SHOOT", "MOVIE", "URBAN", "DOZEN", "FIELD",
  "REACH", "STRIP", "EVERY", "AUDIT", "LAYER",
  "ROMAN", "SUGAR", "SHARP", "CROWN", "LAUGH",
  "SCENE", "UPPER", "RANGE", "STORE", "NIGHT",
  "GOING", "SORRY", "RIVER", "TAKEN", "MIGHT",
  "NOTED", "JOINT", "CLOSE", "PRIDE", "EXACT",
  "UNITY", "PHONE", "SLEEP", "RIVAL", "ADMIT",
  "MAYBE", "SLIDE", "CLEAN", "COULD", "BUILT",
  "BREED", "LEAVE", "FORCE", "FIGHT", "ARGUE",
  "STAFF", "TREND", "FIFTY", "TAXES", "STOOD",
  "IMAGE", "FORTY", "AFTER", "GUESS", "WATCH",
  "ORDER", "PIECE", "EAGER", "COACH", "ANGER",
  "ALIKE", "WOULD", "FIBER", "CRASH", "OCCUR",
  "ANGLE", "TEETH", "SPACE", "FRUIT", "JAPAN",
  "WRONG", "CIVIL", "FORUM", "BUYER", "LUCKY",
  "PROOF", "GREEN", "LARGE", "CHILD", "SMOKE",
  "DREAM", "TODAY", "JUDGE", "PROVE", "ALARM",
  "UNDUE", "APPLY", "DYING", "HUMAN", "DAILY",
  "INPUT", "GUEST", "WHOLE", "LOGIC", "MAKER",
  "VIDEO", "WORST", "PLANT", "RURAL", "THEME",
  "STAKE", "BRIEF", "AMONG", "GROWN", "WOMAN",
  "CYCLE", "BASIS", "ALIVE", "PLACE", "INDEX",
  "LYING", "REFER", "ENEMY", "PRIZE", "UNCLE",
  "NEVER", "HENCE", "THREW", "MOUTH", "LIVES",
  "TASTE", "YIELD", "DEPTH", "QUIET", "FRONT",
  "VOICE", "NEEDS", "MEANT", "LIMIT", "BLOOD",
  "STEAM", "FRAUD", "TRAIN", "CHINA", "CROWD",
  "BREAK", "STORM", "MOTOR", "FORTH", "BROAD",
  "SENSE", "WROTE", "PRICE", "PAPER", "MODEL",
  "THINK", "SOUND", "SPENT", "GREAT", "KNIFE",
  "QUICK", "SIZED", "THOSE", "WHICH", "FRAME",
  "CLICK", "OTHER", "TRACK", "SPLIT", "STUCK",
  "BADLY", "DEATH", "ROYAL", "ENJOY", "PHASE",
  "BAKER", "WORRY", "PLAIN", "CAUSE", "MONTH",
  "CHIEF", "AHEAD", "BASIC", "SKILL", "STUDY",
  "WHEEL", "BOUND", "BEACH", "ASIDE", "TOWER",
  "MAJOR", "MATCH", "SHEET", "PHOTO", "PLATE",
  "GRADE", "DRAMA", "GRANT", "LEGAL", "OCEAN",
  "EXTRA", "IDEAL", "SINCE", "SPOKE", "CARRY",
  "FIXED", "ISSUE", "THEIR", "NEWLY", "QUITE",
  "LEAST", "ARENA", "GIANT", "BROWN", "AGAIN",
  "JONES", "SPORT", "EARTH", "TRUST", "MAGIC",
  "FAULT", "READY", "ALLOW", "TRIES", "RATIO",
  "OFFER", "UNDER", "LOCAL", "UPSET", "SCOOP",
  "WORLD", "HANDS", "ZONES"
];

const nonWords2 = [
  "BLENT", "FRAKE", "GLOME", "TRISK", "PLONE",
  "DRASH", "SMOTE", "CLARN", "BRUDE", "SNARP",
  "GRINT", "FLAGE", "CROND", "BLAFE", "STOOK",
  "SPONE", "TWISK", "GLANT", "THOPE", "CRUSK",
  "FLIRP", "MIVOR", "BRAFT", "PROKE", "DRULL",
  "SNOME", "SPLID", "STROW", "CLUGE", "BRALL",
  "SHABE", "PLISP", "SNUDE", "BLORT", "VOTIY",
  "GRABE", "THRUP", "DRINT", "SKAVE", "GLERM",
  "SMARN", "BRILK", "DRABE", "STAFE", "TROST",
  "PLURE", "BRIKE", "SWABE", "CHORN", "GRALL",
  "SLUVE", "MROPE", "BLISH", "CLANE", "SPLAR",
  "THRIN", "FLOTE", "DRAIL", "CLORN", "SKIRL",
  "TRUSK", "DROKE", "THRALE", "BRUNE", "SMOVE",
  "CRALE", "PRAVE", "GLIVE", "SLORN", "SMAPE",
  "PLERN", "CLURM", "DRONT", "FRUNE", "SKALE",
  "TROLE", "SPAVE", "BROME", "THRIM", "CLOPE",
  "BLORE", "SKUDE", "SNIBE", "PRISH", "GRALED",
  "TWERN", "SLINT", "CHOVE", "BLINT", "CRUNE",
  "DRISK", "STERM", "FLACE", "CLISP", "TRANE",
  "SMORE", "SPLEN", "BRINT", "SNILM", "STELD",
  "DROSH", "GLORN", "BRIVE", "PRALE", "CLARP",
  "SMISH", "GRUTE", "TROBE", "DRALE", "SPLIN",
  "SNISK", "TWORN", "CHIRL", "GROPET", "TRAVE",
  "BRISA", "SNIRD", "SWAPE", "CRONEP", "BLANE",
  "SLARN", "PRUME", "GLUSH", "SNISH", "SPLIR",
  "DRISP", "SNAVE", "THROP", "BRASP", "SLORE",
  "TWABE", "GLINTU", "PLABE", "BLUNE", "DROVET",
  "TRONE", "BRODE", "FRALE", "FLISP", "STAME",
  "GRISH", "CLUSH", "TROSE", "SKARP", "BLOME",
  "PIQIP", "FUVUX", "SUZUB", "QAGIM", "DEWEW",
  "XELUH", "HIXUX", "YUZOB", "RAQED", "TUZEZ",
  "TIRIK", "PEYAG", "LUHIM", "ZEZID", "WENAZ",
  "FADAX", "MORUW", "SASEW", "WIZUL", "YIGEZ",
  "KEHOG", "BOJOM", "YUVON", "DISAN", "COKOX",
  "TIWUB", "WABIL", "PEYOW", "BOLAL", "COJOX",
  "ROQOF", "KECAJ", "LAFIG", "FIFIT", "GINAR",
  "YOHIF", "MAQEQ", "KUSOY", "FIDUS", "QOMER",
  "JEBAC", "BUHAB", "NUXON", "TEZIR", "GURIF",
  "JIBEG", "DEKAG", "ZOHOY", "QINAS", "XUROF",
  "RUJIL", "XITEZ", "CACIL", "LIJEQ", "WUKAH",
  "BUGOG", "TOKIJ", "TUQOY", "DUPUL", "DOROR",
  "VESEM", "KAWOG", "CICIF", "BIXOF", "JUGUN",
  "QIZOF", "BOJUG", "VUSIY", "POVOB", "GEMUR",
  "PINIS", "YAFET", "YIDOC", "TEDEV", "PEFUM",
  "DAPEM", "KESEX", "TIKEZ", "JUHED", "VEPEH",
  "TENUX", "WESAS", "LUVOZ", "GEZAX", "VUROW",
  "HODAP", "XEKEP", "JUPOJ", "XUPEW", "RIVIH",
  "WAWEN", "TOZOW", "YAHOB", "KITUD", "MEZUN",
  "WEDIN", "VENUF", "KOLUF", "VIKAB", "TAWUK",
  "QOJOC", "TINUV", "NEDEW"
];

// Export the arrays
export { realWords1, realWords2, nonWords1, nonWords2 };

/**
 * Get a random real word from block one
 * @returns {string} A random 5-letter real word
 */
export function getRandomBlockOneWord() {
  const randomIndex = Math.floor(Math.random() * realWords1.length);
  return realWords1[randomIndex];
}

/**
 * Get a random non-word from block one
 * @returns {string} A random 5-letter non-word
 */
export function getRandomBlockOneNonWord() {
  const randomIndex = Math.floor(Math.random() * nonWords1.length);
  return nonWords1[randomIndex];
}

/**
 * Get a random real word from block two
 * @returns {string} A random 5-letter real word
 */
export function getRandomBlockTwoWord() {
  const randomIndex = Math.floor(Math.random() * realWords2.length);
  return realWords2[randomIndex];
}

/**
 * Get a random non-word from block two
 * @returns {string} A random 5-letter non-word
 */
export function getRandomBlockTwoNonWord() {
  const randomIndex = Math.floor(Math.random() * nonWords2.length);
  return nonWords2[randomIndex];
}
